server {
    server_name map.bfu-id.ru www.map.bfu-id.ru;
    client_max_body_size 20M;

    location / {
        proxy_redirect off;
        proxy_read_timeout 600;
        proxy_connect_timeout 600;
        send_timeout 600;
        proxy_send_timeout 600;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection $connection_upgrade;
        proxy_pass http://localhost:3070;
    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/map.bfu-id.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/map.bfu-id.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = map.bfu-id.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name map.bfu-id.ru www.map.bfu-id.ru;
    listen 80;
    return 404; # managed by Certbot


}